name: Terraform Deployment

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_organization_name: ${{ secrets.SNOWFLAKE_ORGANIZATION }}
      TF_VAR_account_name: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      TF_VAR_user: ${{ secrets.SNOWFLAKE_USER }}
      TF_VAR_password: ${{ secrets.SNOWFLAKE_PASSWORD }}
      TF_VAR_role: ${{ secrets.SNOWFLAKE_ROLE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
