name: Terraform Deployment

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      TF_VAR_organization_name: ${{ secrets.TF_VAR_ORGANIZATION_NAME }}
      TF_VAR_account_name: ${{ secrets.TF_VAR_ACCOUNT_NAME }}
      TF_VAR_user: ${{ secrets.TF_VAR_USER }}
      TF_VAR_password: ${{ secrets.TF_VAR_PASSWORD }}
      TF_VAR_role: ${{ secrets.TF_VAR_ROLE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Debug Variables
        run: |
          echo "ORG=$TF_VAR_organization_name"
          echo "ACCOUNT=$TF_VAR_account_name"
          echo "USER=$TF_VAR_user"
          echo "ROLE=$TF_VAR_role"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
